;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; FILE
;;; lilypond-src.el
;;; 
;;; DESCRIPTION
;;; An example Aby instruction-file containing some more advanced tricks.
;;;
;;; AUTHOR
;;; Ruben Philipp
;;;
;;; CREATED
;;; 2023-04-02
;;;
;;; $$ Last modified:  22:45:05 Sun Apr  2 2023 CEST
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(let* (;; the file containing the template data
       ;; relative to this instruction-file
       (fragment "lilypond-src.org")
       ;; a list with static-replacements (cf. doc)
       (static-rep '())
       ;; a list with ask-replacements
       (ask-rep '(;; the first element is the symbol for the variable
                  ;; the second element is the replacement-regex
                  ;; the third element is the prompt (optional)
                  ;; the fourth element is a documentation comment (optional)
                  (outfile "{{outfile}}"
                           "Output filename (e.g. fig.pdf): "
                           "The output filename of the parsed lp-file.")
                  (outdir "{{outdir}}"
                          "Output directory (e.g. figures/): ")
                  ;; Here, NIL indicates that the ask-rep does no replacements
                  ;; and just stores the result from the prompt to the 
                  ;; reps-variable generated by aby-insert.
                  ;; This is later accessed during the dynamic replacement
                  ;; (see below).
                  (with-format nil "With formatting snippet? (y/N) ")))
       ;; a list with dynamic replacements
       ;; the function must take the assoc list with
       ;; the replacements as first argument (cf. doc)
       (dynamic-rep
        '((formatting-snippet "{{formatting-snippet}}"
                              '(lambda (reps)
                                 (if (string= "y"
                                              (alist-get 'with-format
                                                         reps))
                                     (file-to-string
                                      (concat
                                       ;; The 'aby-fragment-directory is
                                       ;; the directory of this instruction
                                       ;; file. It is set in aby-insert
                                       ;; (cf. documentation).
                                       (alist-get 'aby-fragment-directory
                                                  reps)
                                       "lilypond-src-formatting-snippet.org"))
                                   ""))
                              "This adds an optional formatting snippet to the ~
                               resulting output"))))
  ;; this constructs the instruction association list
  ;; and must be the return value of this file
  (aby-instruct fragment
                static-rep
                ask-rep
                dynamic-rep))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; EOF lilypond-src.el

